name: Relay (Tradier → Gists)

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - name: Run relay
        env:
          TRADIER_TOKEN: ${{ secrets.TRADIER_TOKEN }}
          FINNHUB_TOKEN: ${{ secrets.FINNHUB_TOKEN }}
          GIST_TOKEN:    ${{ secrets.GIST_TOKEN }}
          GIST_ID_CALENDAR: ${{ secrets.GIST_ID_CALENDAR }}
          GIST_ID_MARKET:   ${{ secrets.GIST_ID_MARKET }}
          TRADIER_BASE: https://api.tradier.com/v1
        run: python relay_us_options_tradier.py
